# Site Build Settings

# jekyll-paginate configuration
paginate: 5

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax

# Your other configurations

highlighter: rouge
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

usemathjax : true

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)
title: "Lăng Kính Thiểu Năng"
description: "Khoa học dưới góc nhìn thiểu năng"
author: "Luvich"

# RSS 2.0 can be used instead of Atom by uncommenting following two lines
# feed:
#   path: rss-feed.xml

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      categories: ["maths", "algebra"]
