# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'luvich'
  #'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
  - name: 'Toán học'
    url: '/maths'
    submenu:
      - name: 'Đại số'
        url: '/maths/algebra'
        submenu:
          - name: 'Đại số tuyến tính'
            url: '/linear-algebra'
          - name: 'Đại số trừu tượng'
            url: '/abstract-algebra'
      - name: 'Hình học'
        url: '/geometry'
  - name: 'Machine Learning'
    url: '/machine-learning'
  - name: 'Toán sơ cấp'
    url: '/elementary'
  - name: 'Luvich'
    url: '/about'
  - name: 'Liên hệ'
    url: '/contact'

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
  - icon: 'twitter'
    link: 'https://x.com/hoathekiet'
  - icon: 'facebook'
    link: 'https://www.facebook.com/hoathekiet/'
  - icon: 'instagram'
    link: 'https://www.instagram.com/hoathekiet/'
  # - icon: 'envelope'
  #   link: 'chuongluong266@gmail.com'
  # - icon: 'rss-square'
  #   link: ''
  # - icon: 'rss-square'
  #   link: 'rss-feed.xml'

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'
related_posts: 'You may also enjoy...'
post_date_prefix: 'Written on'
