# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'luvich'
  #'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
  - name: 'Mathematics'
    url: '/maths'
    submenu:
      - name: 'Algebra'
        url: '/maths/algebra'
        submenu:
          - name: 'Linear Algebra'
            url: '/maths/algebra/linear-algebra'
          - name: 'Abstract Algebra'
            url: '/maths/algebra/abstract-algebra'
      - name: 'Geometry'
        url: '/geometry'
        submenu:
          - name: 'Topology'
            url: '/maths/geometry/topology'
          - name: 'Algebraic Geometry'
            url: '/maths/geometry/algebraic-geometry'
          - name: 'Differential Geometry'
            url: '/maths/geometry/differential-geometry'
  - name: 'Machine Learning'
    url: '/machine-learning'
    submenu:
      - name: 'Supervised ML'
        url: '/maths/geometry/supervised-ml'
      - name: 'Unsupervised ML'
        url: '/maths/geometry/unsupervised-ml'
      - name: 'Reinforcement Learning'
        url: '/maths/geometry/reinforcement-learning'
  - name: 'Language'
    url: '/language'
  - name: 'Luvich'
    url: '/about'
  - name: 'Contact'
    url: '/contact'

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
  - icon: 'twitter'
    link: 'https://x.com/hoathekiet'
  - icon: 'facebook'
    link: 'https://www.facebook.com/hoathekiet/'
  - icon: 'instagram'
    link: 'https://www.instagram.com/hoathekiet/'
  # - icon: 'envelope'
  #   link: 'chuongluong266@gmail.com'
  # - icon: 'rss-square'
  #   link: ''
  # - icon: 'rss-square'
  #   link: 'rss-feed.xml'

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'
related_posts: 'You may also enjoy...'
post_date_prefix: 'Written on'
